src/readelectronversion.js, test/readelectronversion.js
I found this while trying to port `electron-installer-snap` over to use `electron-installer-common`.
This is a breaking change to the API, and I'm going to release 0.3.0 after this is merged.
=> Don't require an options object to use readElectronVersion

src/dependencies.js, test/dependencies.js
Its return value used Debian-specific syntax, so it was changed to return a list of values that can be transformed in the installer module.
As a result, installer modules must `.concat()` the transformed value onto the dependency list.
This is required in order for `electron-installer-redhat` to use `getDepends`.
This is a breaking API change.
=> Extract getTrashDepends from getDepends

src/index.js, test/installer.js
Fixes https://github.com/electron-userland/electron-installer-debian/issues/168 by erroring if the binary symlink is invalid.
=> Check that createBinary symlinks to an existing Electron app binary

src/index.js
This is basically #5, except that it doesn't move all of the non-export code out of `src/index.js`, and there are no merge conflicts. Tested by changing the code in `-debian`, `-redhat`, and `-snap` to use the re-exported functions.
No breaking changes.
Closes #5.
=> Re-export public functions not already in src/index.js

src/index.js, src/replacescopename.js, src/sanitizename.js, test/replacescopename.js, test/sanitizename.js
* The default divider for `replaceScopeName` should be `-`, not `_` (per https://github.com/electron-userland/electron-installer-common/pull/1#discussion_r245060183)
* Adds a `sanitizeName` function (which also calls `replaceScopeName`). Addresses https://github.com/electron-userland/electron-forge/issues/654
=> Add sanitize name function & fix default replaceScopeName divider

src/error.js, test/error.js
Without this change, calling `new Error` causes the original backtrace to disappear and makes it more difficult to track down where the exception was thrown.
=> Retain original backtrace when using wrapError

package.json, src/desktop.js, src/index.js, src/installer.js, test/_util.js, test/desktop.js, test/installer.js, test/template.js
Refactors most of the functions in `src/index.js` into a structured class. Installer modules can be subclassed.
I have successfully converted 4 of the known `electron-installer-*` modules to use this:
* `-debian`
* `-redhat`
* `-flatpak` _(my fork of it)_
* `-windows` _(a fork of the current `-common` PR)_
I designed `-snap` a bit differently, so I'm only using extracted functions, but I think this (large) change is ready for some review.
Fixes #8.
=> Installer class

package.json
@fcastilloec I'm fast-tracking this because I was a part of the upgrade, I know what's in it, and the upgrade in this module wasn't as bad as it was in Packager, since `asar.extractFile` is sync and so really didn't change. The important thing is that `asar@1.0.0` removes a package with a security vulnerability.
=> Upgrade asar to ^1.0.0

src/installer.js, test/installer.js
Generic version of electron-userland/electron-installer-debian#184 and electron-userland/electron-installer-redhat#112, with tests.
To use, you need to override `copyApplication` similar to how it was initially done in the referenced PRs, except with less code.
CC: @nornagon
=> feat: add sandbox helper permission updater

src/index.js, src/installer.js, src/sandboxhelper.js
Needed for use in `electron-installer-snap`, which does not use `ElectronInstaller`.
=> feat: add updateSandboxHelperPermissions outside of ElectronInstaller

.travis.yml, README.md, package.json, src/desktop.js, src/error.js, src/installer.js, src/readelectronversion.js, src/readmetadata.js, src/sandboxhelper.js, src/spawn.js, src/template.js, test/_util.js, test/desktop.js, test/error.js, test/installer.js, test/readelectronversion.js, test/readmetadata.js, test/spawn.js, test/template.js
BREAKING CHANGE: Drops support for Node < 8.
* Convert to `async`/`await` syntax
* Adjust `wrapError` to be more `async`/`await` - friendly
* Drop `glob-promise` in favor of `util.promisify`
* Update dependencies which require Node >= 8
Closes #22.
Closes #24.
Closes #28.
=> feat: add Node 8 syntax support

.travis.yml
@malept I noticed that the majority of the previous PRs were failing on Travis because of this issue. It's because of the switch to `yarn` rather than using `npm`.
Nonetheless, maybe we should consider blocking merging PR that fail Travis testing now that this PR fixes it.
=> Travis: fix windows builds failing even after success

src/defaults.js, test/defaults.js
=> fix: let implementing modules specify revision fallbacks

NEWS.md, src/installer.js, test/installer.js
Electron Forge needs to know what the final paths of the distributables that `electron-installer-*` generate, so it can do things like publish to service X. Since `-debian` and `-redhat` have options that allow a user to customize what the name is, the installer modules need to pass back the resulting package file paths.
=> feat: add packagePaths to options when calling ElectronInstaller.movePackage()

src/dependencies.js, test/dependencies.js
For RPMs at least, different distributions may have slightly different names for effectively the same package.
See https://github.com/electron-userland/electron-installer-redhat/issues/130
=> fix: allow multiple package names for trash dependencies

src/dependencies.js, test/dependencies.js
We will also have to upgrade `-debian` and `-redhat` to use this.
=> fix(dependencies): remove UUID dependency for Electron >=8.0.0-beta.1

src/installer.js, test/installer.js
Needed in the case where we introspect the source directory when generating defaults.
=> fix(installer): allow sourceDir to be used before options is set

package.json, src/index.js, src/installer.js, src/sandboxhelper.js, test/sandboxhelper.js
BREAKING CHANGE: now requires Node 8.3.0 instead of Node 8.0.0, due to the use of Object spread properties.
=> feat(sandboxhelper): add hasSandboxHelper

package.json, src/spawn.js
`cross-spawn-promise` hasn't been updated in over 2 years and is stuck on an old version of `cross-spawn`. Additionally, it has an issue with its TypeScript definition in that you can't specify several options _(not that it's a problem here, but I ran into it elsewhere)_.
=> refactor: replace cross-spawn-promise with cross-spawn

src/spawn.js, test/spawn.js
BREAKING CHANGE: merges `logger` and `updateErrorCallback` options into the spawn `options` object.
=> feat(spawn): add support for spawn options

src/installer.js, test/installer.js
See https://developer.gnome.org/ThemedIcons/ for more info on symbolic icons. We currently only support `SVG` for this type of icons, since it's the preferred one.
=> feat(installer): add support for symbolic icons

.eslintrc.typescript.js, .github/workflows/ci.yml, package.json, src/index.d.ts, test/index.test-d.ts
Needed so this module can be used in TypeScript projects (my use case for this is Electron Forge).
After this PR, I plan on adding a separate PR to generate API docs similar to https://github.com/electron/electron-packager/pull/1131.
=> feat: add TypeScript definition

package.json, src/readmetadata.js
Replaces the old `asar` npm package with `@electron/asar`, since all new versions from `3.2.1` onwards are being published to the latter.
Users of `@electron-forge/maker-deb`, `@electron-forge/maker-rpm`, and `@electron-forge/maker-snap` are currently stuck with `asar@3.2.0`, which was the latest published version of that package (and potentially have both packages installed, as Forge has already migrated to `@electron/asar` via `electron-packager`).
=> chore: replace `asar` with `@electron/asar`

.github/workflows/ci.yml
Fast follow-up to #196
Since we call the CI workflow from `release.yml` (which gets run on `main` push), we don't need a separate `main` push trigger for the CI workflow file itself.
https://github.com/electron-userland/electron-installer-common/blob/64210b8a48378c4b60ddfd5c9b7319c0d3e83227/.github/workflows/release.yml#L8-L10
=> ci: deduplicate tests on `main` push
